# maps the hyphenated song to the song

song_dict = {
    "tim-mcgraw": "Tim McGraw",
    "picture-to-burn": "Picture to Burn",
    "teardrops-on-my-guitar": "Teardrops on My Guitar",
    "a-place-in-this-world": "A Place in This World",
    "cold-as-you": "Cold as You",
    "the-outside": "The Outside",
    "tied-together-with-a-smile": "Tied Together with a Smile",
    "stay-beautiful": "Stay Beautiful",
    "shouldve-said-no": "Should've Said No",
    "marys-song-oh-my-my-my": "Mary's Song (Oh My My My)",
    "our-song": "Our Song",
    "im-only-me-when-im-with-you": "I'm Only Me When I'm With You",
    "invisible": "Invisible",
    "a-perfectly-good-heart": "A Perfectly Good Heart",
    "fearless-taylors-version": "Fearless",
    "fifteen-taylors-version": "Fifteen",
    "love-story-taylors-version": "Love Story",
    "hey-stephen-taylors-version": "Hey Stephen",
    "white-horse-taylors-version": "White Horse",
    "you-belong-with-me-taylors-version": "You Belong with Me",
    "breathe-taylors-version": "Breathe",
    "tell-me-why-taylors-version": "Tell Me Why",
    "youre-not-sorry-taylors-version": "You're Not Sorry",
    "the-way-i-loved-you-taylors-version": "The Way I Loved You",
    "forever-and-always-taylors-version": "Forever & Always",
    "the-best-day-taylors-version": "The Best Day",
    "change-taylors-version": "Change",
    "jump-then-fall-taylors-version": "Jump Then Fall",
    "untouchable-taylors-version": "Untouchable",
    "come-in-with-the-rain-taylors-version": "Come in with the Rain",
    "superstar-taylors-version": "Superstar",
    "the-other-side-of-the-door-taylors-version": "The Other Side of the Door",
    "today-was-a-fairytale-taylors-version": "Today Was a Fairytale",
    "you-all-over-me-taylors-version-from-the-vault": "You All Over Me",
    "mr-perfectly-fine-taylors-version-from-the-vault": "Mr. Perfectly Fine",
    "we-were-happy-taylors-version-from-the-vault": "We Were Happy",
    "thats-when-taylors-version-from-the-vault": "That's When",
    "dont-you-taylors-version-from-the-vault": "Don't You",
    "bye-bye-baby-taylors-version-from-the-vault": "Bye Bye Baby",
    "if-this-was-a-movie-taylors-version": "If This Was a Movie",
    "mine-taylors-version": "Mine",
    "sparks-fly-taylors-version": "Sparks Fly",
    "back-to-december-taylors-version": "Back to December",
    "speak-now-taylors-version": "Speak Now",
    "dear-john-taylors-version": "Dear John",
    "mean-taylors-version": "Mean",
    "the-story-of-us-taylors-version": "The Story of Us",
    "never-grow-up-taylors-version": "Never Grow Up",
    "enchanted-taylors-version": "Enchanted",
    "better-than-revenge-taylors-version": "Better than Revenge",
    "innocent-taylors-version": "Innocent",
    "haunted-taylors-version": "Haunted",
    "last-kiss-taylors-version": "Last Kiss",
    "long-live-taylors-version": "Long Live",
    "ours-taylors-version": "Ours",
    "superman-taylors-version": "Superman",
    "electric-touch-taylors-version-from-the-vault": "Electric Touch",
    "when-emma-falls-in-love-taylors-version-from-the-vault": "When Emma Falls in Love",
    "i-can-see-you-taylors-version-from-the-vault": "I Can See You",
    "castles-crumbling-taylors-version-from-the-vault": "Castles Crumbling",
    "foolish-one-taylors-version-from-the-vault": "Foolish One",
    "timeless-taylors-version-from-the-vault": "Timeless",
    "safe-and-sound-taylors-version": "Safe & Sound",
    "eyes-open-taylors-version": "Eyes Open",
    "state-of-grace-taylors-version": "State of Grace",
    "red-taylors-version": "Red",
    "treacherous-taylors-version": "Treacherous",
    "i-knew-you-were-trouble-taylors-version": "I Knew You Were Trouble",
    "all-too-well-taylors-version": "All Too Well",
    "22-taylors-version": "22",
    "i-almost-do-taylors-version": "I Almost Do",
    "we-are-never-ever-getting-back-together-taylors-version": "We Are Never Ever Getting Back Together",
    "stay-stay-stay-taylors-version": "Stay Stay Stay",
    "the-last-time-taylors-version": "The Last Time",
    "holy-ground-taylors-version": "Holy Ground",
    "sad-beautiful-tragic-taylors-version": "Sad Beautiful Tragic",
    "the-lucky-one-taylors-version": "The Lucky One",
    "everything-has-changed-taylors-version": "Everything Has Changed",
    "starlight-taylors-version": "Starlight",
    "begin-again-taylors-version": "Begin Again",
    "the-moment-i-knew-taylors-version": "The Moment I Knew",
    "come-back-be-here-taylors-version": "Come Back... Be Here",
    "girl-at-home-taylors-version": "Girl at Home",
    "ronan-taylors-version": "Ronan",
    "better-man-taylors-version-from-the-vault": "Better Man",
    "nothing-new-taylors-version-from-the-vault": "Nothing New",
    "babe-taylors-version-from-the-vault": "Babe",
    "message-in-a-bottle-taylors-version-from-the-vault": "Message in a Bottle",
    "i-bet-you-think-about-me-taylors-version-from-the-vault": "I Bet You Think About Me",
    "forever-winter-taylors-version-from-the-vault": "Forever Winter",
    "run-taylors-version-from-the-vault": "Run",
    "the-very-first-night-taylors-version-from-the-vault": "The Very First Night",
    "all-too-well-10-minute-version-taylors-version-from-the-vault": "All Too Well (10 Minute Version)",
    "welcome-to-new-york-taylors-version": "Welcome to New York",
    "blank-space-taylors-version": "Blank Space",
    "style-taylors-version": "Style",
    "out-of-the-woods-taylors-version": "Out of the Woods",
    "all-you-had-to-do-was-stay-taylors-version": "All You Had to Do Was Stay",
    "shake-it-off-taylors-version": "Shake It Off",
    "i-wish-you-would-taylors-version": "I Wish You Would",
    "bad-blood-taylors-version": "Bad Blood",
    "wildest-dreams-taylors-version": "Wildest Dreams",
    "how-you-get-the-girl-taylors-version": "How You Get the Girl",
    "this-love-taylors-version": "This Love",
    "i-know-places-taylors-version": "I Know Places",
    "clean-taylors-version": "Clean",
    "wonderland-taylors-version": "Wonderland",
    "you-are-in-love-taylors-version": "You Are In Love",
    "new-romantics-taylors-version": "New Romantics",
    "slut-taylors-version-from-the-vault": "Slut!",
    "say-dont-go-taylors-version-from-the-vault": "Say Don't Go",
    "now-that-we-dont-talk-taylors-version-from-the-vault": "Now That We Don't Talk",
    "suburban-legends-taylors-version-from-the-vault": "Suburban Legends",
    "is-it-over-now-taylors-version-from-the-vault": "Is It Over Now?",
    "ready-for-it": "...Ready For It?",
    "end-game": "End Game",
    "i-did-something-bad": "I Did Something Bad",
    "dont-blame-me": "Don't Blame Me",
    "delicate": "Delicate",
    "look-what-you-made-me-do": "Look What You Made Me Do",
    "so-it-goes": "So It Goes...",
    "gorgeous": "Gorgeous",
    "getaway-car": "Getaway Car",
    "king-of-my-heart": "King Of My Heart",
    "dancing-with-our-hands-tied": "Dancing With Our Hands Tied",
    "dress": "Dress",
    "this-is-why-we-cant-have-nice-things": "This Is Why We Can't Have Nice Things",
    "call-it-what-you-want": "Call It What You Want",
    "new-years-day": "New Year's Day",
    "i-forgot-that-you-existed": "I Forgot That You Existed",
    "cruel-summer": "Cruel Summer",
    "lover": "Lover",
    "the-man": "The Man",
    "the-archer": "The Archer",
    "i-think-he-knows": "I Think He Knows",
    "miss-americana-and-the-heartbreak-prince": "Miss Americana & the Heartbreak Prince",
    "paper-rings": "Paper Rings",
    "cornelia-street": "Cornelia Street",
    "death-by-a-thousand-cuts": "Death by a Thousand Cuts",
    "london-boy": "London Boy",
    "soon-youll-get-better": "Soon You'll Get Better",
    "false-god": "False God",
    "you-need-to-calm-down": "You Need to Calm Down",
    "afterglow": "Afterglow",
    "me": "ME!",
    "its-nice-to-have-a-friend": "It's Nice to Have a Friend",
    "daylight": "Daylight",
    "all-of-the-girls-you-loved-before": "All of the Girls You Loved Before",
    "the-1": "the 1",
    "cardigan": "cardigan",
    "the-last-great-american-dynasty": "the last great american dynasty",
    "exile": "exile",
    "my-tears-ricochet": "my tears ricochet",
    "mirrorball": "mirrorball",
    "seven": "seven",
    "august": "august",
    "this-is-me-trying": "this is me trying",
    "illicit-affairs": "illicit affairs",
    "invisible-string": "invisible string",
    "mad-woman": "mad woman",
    "epiphany": "epiphany",
    "betty": "betty",
    "peace": "peace",
    "hoax": "hoax",
    "the-lakes": "the lakes",
    "willow": "willow",
    "champagne-problems": "champagne problems",
    "gold-rush": "gold rush",
    "tis-the-damn-season": "tis the damn season",
    "tolerate-it": "tolerate it",
    "no-body-no-crime": "no body, no crime",
    "happiness": "happiness",
    "dorothea": "dorothea",
    "coney-island": "coney island",
    "ivy": "ivy",
    "cowboy-like-me": "cowboy like me",
    "long-story-short": "long story short",
    "marjorie": "marjorie",
    "closure": "closure",
    "evermore": "evermore",
    "right-where-you-left-me": "right where you left me",
    "its-time-to-go": "it's time to go",
    "lavender-haze": "Lavender Haze",
    "maroon": "Maroon",
    "anti-hero": "Anti-Hero",
    "snow-on-the-beach": "Snow On the Beach",
    "youre-on-your-own-kid": "You're On Your Own, Kid",
    "midnight-rain": "Midnight Rain",
    "question": "Question...?",
    "vigilante-shit": "Vigilante Shit",
    "bejeweled": "Bejeweled",
    "labyrinth": "Labyrinth",
    "karma": "Karma",
    "sweet-nothing": "Sweet Nothing",
    "mastermind": "Mastermind",
    "hits-different": "Hits Different",
    "the-great-war": "The Great War",
    "bigger-than-the-whole-sky": "Bigger Than the Whole Sky",
    "paris": "Paris",
    "high-infidelity": "High Infidelity",
    "glitch": "Glitch",
    "wouldve-couldve-shouldve": "Would've, Could've, Should've",
    "dear-reader": "Dear Reader",
    "youre-losing-me-from-the-vault": "You're Losing Me"
}


# albums = [
#     "taylor_swift",
#     "fearless",
#     "speak_now",
#     "red",
#     "1989",
#     "reputation",
#     "lover",
#     "folklore",
#     "evermore",
#     "midnights",
# ]
#
# for album in albums:
#     with open(f"songs_list/{album}.txt", "r") as songs, open(
#         f"songs_dict/{album}.txt", "r"
#     ) as titles:
#         for key, value in zip(songs, titles):
#             key = key.strip()
#             value = value.strip()
#             song_dict[key] = value
#
# for key, val in song_dict.items():
#     print("\"" + key + "\": \"" + val + "\",")
